/**
 * Registro central de códigos de error (Doc 14 — cierra el gap de
 * auditoría del corpus 01-24: sin esto, los ~35+ códigos existentes solo
 * vivían como convención textual dispersa entre SQL (`raise exception
 * 'CODIGO: mensaje'`) y TS (`errorResponse(status, 'CODIGO', ...)`),
 * verificable solo por grep, nunca por el compilador ni por un test.
 *
 * Sin dependencias runtime — importable tanto desde paquetes Node
 * (vía dist/) como directo desde Deno (Edge Functions), igual que
 * database.generated.ts.
 *
 * AD-35 (Doc 14, mitad "versionado"): sin versionado de API en v0 — un
 * único cliente propietario (apps/web) desplegado junto a las Edge
 * Functions; se adopta cuando exista un segundo consumidor externo real
 * (AD-23). Un código de error que cambia de semántica se retira (nunca se
 * reutiliza el nombre) y se añade uno nuevo — no hace falta un esquema de
 * versión aparte mientras el único consumidor se despliega en el mismo
 * commit que el servidor.
 *
 * tests/governance/error-codes-coverage.test.ts escanea `supabase/` y
 * falla si aparece un código nuevo que no esté aquí — mantener esta lista
 * al día no es opcional, es lo que el test verifica.
 *
 * GENERADO A MANO, no por introspección — a diferencia de
 * database.generated.ts, no hay una fuente única de verdad estructural
 * para extraer esto (los códigos viven en strings SQL y TS). Regenerar
 * manualmente si el test-guardia falla.
 */

export const ERROR_CODES = {
  // ── Transversal (rate limiting, contrato HTTP, autenticación) ─────────
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // ── Tenancy / membresías / invitaciones (Fase I) ───────────────────────
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INVITE_PENDING: 'INVITE_PENDING',
  INV_EMAIL_MISMATCH: 'INV_EMAIL_MISMATCH',
  INV_EXPIRED: 'INV_EXPIRED',
  INV_NOT_FOUND: 'INV_NOT_FOUND',
  INV_NOT_PENDING: 'INV_NOT_PENDING',
  INV_USED: 'INV_USED',
  LAST_AGENT: 'LAST_AGENT',
  MEMBERSHIP_FETCH_FAILED: 'MEMBERSHIP_FETCH_FAILED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  NO_MEMBERSHIP: 'NO_MEMBERSHIP',
  PRIVILEGE_ESCALATION: 'PRIVILEGE_ESCALATION',
  SELF_MODIFY: 'SELF_MODIFY',
  SLUG_INVALID: 'SLUG_INVALID',
  SLUG_TAKEN: 'SLUG_TAKEN',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',

  // ── Guards de dominio genéricos ─────────────────────────────────────────
  APPEND_ONLY: 'APPEND_ONLY',
  // Lo levantan siete guards distintos (prescripción, transferencias, legal
  // holds, procedencia de terceros, actuaciones, acuerdos de pago y fondos)
  // con el mismo significado: el documento referenciado es de otro tenant.
  DOCUMENTO_INVALIDO: 'DOCUMENTO_INVALIDO',
  INVALID_INSERT: 'INVALID_INSERT',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_UPDATE: 'INVALID_UPDATE',

  // ── Motor Presupuestal (GAP-19) ─────────────────────────────────────────
  BUDGET_NOT_RECONCILED: 'BUDGET_NOT_RECONCILED',
  COEFICIENTE_SET_NO_VIGENTE: 'COEFICIENTE_SET_NO_VIGENTE',
  DISTRIBUCION_INVALIDA: 'DISTRIBUCION_INVALIDA',
  FINANCIACION_EXCEDE_PRESUPUESTO: 'FINANCIACION_EXCEDE_PRESUPUESTO',
  FONDO_IMPREVISTOS_NO_EXISTE: 'FONDO_IMPREVISTOS_NO_EXISTE',
  FONDO_INSUFICIENTE: 'FONDO_INSUFICIENTE',
  IMMUTABLE_BUDGET: 'IMMUTABLE_BUDGET',
  IMMUTABLE_COEFFICIENT_SET: 'IMMUTABLE_COEFFICIENT_SET',
  IMMUTABLE_POLICY: 'IMMUTABLE_POLICY',
  NECESIDAD_NEGATIVA: 'NECESIDAD_NEGATIVA',
  POLITICA_NO_VIGENTE: 'POLITICA_NO_VIGENTE',
  PRESUPUESTO_NO_ENCONTRADO: 'PRESUPUESTO_NO_ENCONTRADO',
  SIN_COEFICIENTE: 'SIN_COEFICIENTE',
  SIN_INMUEBLES: 'SIN_INMUEBLES',

  // ── Dominio Fondos (GAP-22, PLAN §4.3) ───────────────────────────────────
  // FONDO_IMPREVISTOS_NO_EXISTE y FONDO_INSUFICIENTE viven arriba: nacieron
  // con el Motor Presupuestal (FI-003) y siguen siendo suyos.
  AUTORIZACION_INVALIDA: 'AUTORIZACION_INVALIDA',
  // R9: comprometer más de lo que el fondo tiene disponible (saldo - comprometido).
  COMPROMISO_EJECUCION_EXCEDE_MONTO: 'COMPROMISO_EJECUCION_EXCEDE_MONTO',
  COMPROMISO_ESTADO_NO_EJECUTABLE: 'COMPROMISO_ESTADO_NO_EJECUTABLE',
  COMPROMISO_ESTADO_TERMINAL: 'COMPROMISO_ESTADO_TERMINAL',
  COMPROMISO_EXCEDE_DISPONIBLE: 'COMPROMISO_EXCEDE_DISPONIBLE',
  COMPROMISO_INVALIDO: 'COMPROMISO_INVALIDO',
  COMPROMISO_TRANSICION_INVALIDA: 'COMPROMISO_TRANSICION_INVALIDA',
  EXTRACTO_LINEA_INVALIDA: 'EXTRACTO_LINEA_INVALIDA',
  FONDO_ESTADO_NO_ADMITE_COMPROMISOS: 'FONDO_ESTADO_NO_ADMITE_COMPROMISOS',
  FONDO_ESTADO_NO_ADMITE_MOVIMIENTOS: 'FONDO_ESTADO_NO_ADMITE_MOVIMIENTOS',
  FONDO_ESTADO_NO_ADMITE_SOLICITUDES: 'FONDO_ESTADO_NO_ADMITE_SOLICITUDES',
  FONDO_ESTADO_TERMINAL: 'FONDO_ESTADO_TERMINAL',
  FONDO_MOTIVO_REQUERIDO: 'FONDO_MOTIVO_REQUERIDO',
  FONDO_NATURALEZA_INVALIDA: 'FONDO_NATURALEZA_INVALIDA',
  FONDO_NO_ENCONTRADO: 'FONDO_NO_ENCONTRADO',
  FONDO_REVERSION_INVALIDA: 'FONDO_REVERSION_INVALIDA',
  // R8: saldo_actual no se escribe a mano, se deriva de fondo_movimientos.
  FONDO_SALDO_DERIVADO: 'FONDO_SALDO_DERIVADO',
  FONDO_TENANT_INCONSISTENTE: 'FONDO_TENANT_INCONSISTENTE',
  FONDO_TRANSICION_INVALIDA: 'FONDO_TRANSICION_INVALIDA',
  ORGANO_DECISORIO_INVALIDO: 'ORGANO_DECISORIO_INVALIDO',
  // D-37: segregación de funciones de las solicitudes de uso de fondos.
  SOLICITUD_AUTOAPROBACION: 'SOLICITUD_AUTOAPROBACION',
  SOLICITUD_AUTOEJECUCION: 'SOLICITUD_AUTOEJECUCION',
  // 'ejecutada' solo la deriva la ejecución completa del compromiso vinculado.
  SOLICITUD_EJECUTADA_NO_MANUAL: 'SOLICITUD_EJECUTADA_NO_MANUAL',
  SOLICITUD_ESTADO_TERMINAL: 'SOLICITUD_ESTADO_TERMINAL',
  // Modelo §20: no se aprueba una solicitud que exceda el disponible.
  SOLICITUD_EXCEDE_DISPONIBLE: 'SOLICITUD_EXCEDE_DISPONIBLE',
  SOLICITUD_MOTIVO_REQUERIDO: 'SOLICITUD_MOTIVO_REQUERIDO',
  SOLICITUD_ROL_INSUFICIENTE: 'SOLICITUD_ROL_INSUFICIENTE',
  SOLICITUD_TRANSICION_INVALIDA: 'SOLICITUD_TRANSICION_INVALIDA',
  // Compartido con el dominio jurídico/terceros (mismo significado que DOCUMENTO_INVALIDO):
  // el tercero referenciado no pertenece al tenant.
  TERCERO_INVALIDO: 'TERCERO_INVALIDO',
  TIPO_FONDO_INVALIDO: 'TIPO_FONDO_INVALIDO',
  TIPO_FUENTE_FONDO_INVALIDO: 'TIPO_FUENTE_FONDO_INVALIDO',

  // ── Árbol de cuentas presupuestales (E8) ─────────────────────────────────
  CUENTA_INEXISTENTE: 'CUENTA_INEXISTENTE',
  CUENTA_PADRE_INEXISTENTE: 'CUENTA_PADRE_INEXISTENTE',
  CUENTA_TENANT_INCONSISTENTE: 'CUENTA_TENANT_INCONSISTENTE',
  CUENTA_NO_ES_HOJA: 'CUENTA_NO_ES_HOJA',
  CUENTA_NATURALEZA_MEZCLADA: 'CUENTA_NATURALEZA_MEZCLADA',
  CUENTA_NATURALEZA_INVALIDA: 'CUENTA_NATURALEZA_INVALIDA',
  CUENTA_PROFUNDIDAD_MAXIMA: 'CUENTA_PROFUNDIDAD_MAXIMA',
  CUENTA_PROFUNDIDAD_EXCEDIDA: 'CUENTA_PROFUNDIDAD_EXCEDIDA',
  CUENTA_CICLO: 'CUENTA_CICLO',
  CUENTA_TIENE_CONCEPTO: 'CUENTA_TIENE_CONCEPTO',
  CONCEPTO_INEXISTENTE: 'CONCEPTO_INEXISTENTE',
  CONCEPTO_TENANT_INCONSISTENTE: 'CONCEPTO_TENANT_INCONSISTENTE',

  // ── Plan de cuentas contable (PC-1) ──────────────────────────────────────
  // Catálogo distinto del presupuestal: aquí la jerarquía la impone el propio código numérico
  // (5505 cuelga de 55, que cuelga de 5), no un parent_id libre — de ahí que los códigos de
  // error hablen de niveles y prefijos y no de hojas ni de naturaleza mezclada.
  CUENTA_RAIZ_INVALIDA: 'CUENTA_RAIZ_INVALIDA',
  CUENTA_LONGITUD_INVALIDA: 'CUENTA_LONGITUD_INVALIDA',
  CUENTA_NIVEL_SALTADO: 'CUENTA_NIVEL_SALTADO',
  CUENTA_CODIGO_INCOHERENTE: 'CUENTA_CODIGO_INCOHERENTE',
  CUENTA_AGRUPA_SUBCUENTAS: 'CUENTA_AGRUPA_SUBCUENTAS',
  // Instanciación del plan por copropiedad (fn_instanciar_plan_contable, PC-2)
  PLAN_CONTABLE_INEXISTENTE: 'PLAN_CONTABLE_INEXISTENTE',
  TENANT_INEXISTENTE: 'TENANT_INEXISTENTE',

  // ── Puentes hacia el plan contable (PC-3) ────────────────────────────────
  // Los emite validar_cuenta_contable_destino(), compartida por presupuesto_cuenta,
  // fondos, cuentas_bancarias y contable_cuenta_default.
  CUENTA_CONTABLE_INEXISTENTE: 'CUENTA_CONTABLE_INEXISTENTE',
  CUENTA_CONTABLE_TENANT_INCONSISTENTE: 'CUENTA_CONTABLE_TENANT_INCONSISTENTE',
  CUENTA_CONTABLE_NO_ADMITE_MOVIMIENTO: 'CUENTA_CONTABLE_NO_ADMITE_MOVIMIENTO',
  CUENTA_CONTABLE_INACTIVA: 'CUENTA_CONTABLE_INACTIVA',
  CUENTA_CONTABLE_CLASE_INCOMPATIBLE: 'CUENTA_CONTABLE_CLASE_INCOMPATIBLE',
  // GAP-22: la cuenta no tiene requiere_fondo activo pese a que el evento
  // contable o la tabla (fondos) exigen la dimensión Fondos.
  CUENTA_SIN_DIMENSION_FONDO: 'CUENTA_SIN_DIMENSION_FONDO',
  EVENTO_CONTABLE_INVALIDO: 'EVENTO_CONTABLE_INVALIDO',
  // Hace cumplir en el motor una decisión de diseño ya fundamentada (PC-9): impide recrear por
  // tenant un código de cuenta que la plantilla global retiró por doctrina (ej. grupo 27/32).
  CUENTA_CODIGO_RETIRADO: 'CUENTA_CODIGO_RETIRADO',

  // ── Contrapartida de la ejecución presupuestal (PC-4) ────────────────────
  // Sin contrapartida el movimiento tiene débito y ningún crédito: no es exportable.
  LIQUIDACION_REQUERIDA: 'LIQUIDACION_REQUERIDA',
  LIQUIDACION_CUENTA_BANCARIA_REQUERIDA: 'LIQUIDACION_CUENTA_BANCARIA_REQUERIDA',
  LIQUIDACION_CUENTA_BANCARIA_NO_APLICA: 'LIQUIDACION_CUENTA_BANCARIA_NO_APLICA',
  LIQUIDACION_TERCERO_REQUERIDO: 'LIQUIDACION_TERCERO_REQUERIDO',
  CUENTA_BANCARIA_INEXISTENTE: 'CUENTA_BANCARIA_INEXISTENTE',
  CUENTA_BANCARIA_TENANT_INCONSISTENTE: 'CUENTA_BANCARIA_TENANT_INCONSISTENTE',
  CUENTA_BANCARIA_INACTIVA: 'CUENTA_BANCARIA_INACTIVA',
  TERCERO_INEXISTENTE: 'TERCERO_INEXISTENTE',
  TERCERO_TENANT_INCONSISTENTE: 'TERCERO_TENANT_INCONSISTENTE',
  FECHA_DOCUMENTO_FUERA_DE_EJERCICIO: 'FECHA_DOCUMENTO_FUERA_DE_EJERCICIO',

  // ── Ejecución presupuestal (E9) ──────────────────────────────────────────
  PERIODO_INEXISTENTE: 'PERIODO_INEXISTENTE',
  PERIODO_TENANT_INCONSISTENTE: 'PERIODO_TENANT_INCONSISTENTE',
  CUENTA_CONCEPTO_AUTOMATICO: 'CUENTA_CONCEPTO_AUTOMATICO',
  REVERSION_SIN_ORIGEN: 'REVERSION_SIN_ORIGEN',
  REVERSION_CUENTA_DISTINTA: 'REVERSION_CUENTA_DISTINTA',
  MOVIMIENTO_INEXISTENTE: 'MOVIMIENTO_INEXISTENTE',
  MOVIMIENTO_TENANT_INCONSISTENTE: 'MOVIMIENTO_TENANT_INCONSISTENTE',

  // ── Liquidación (F5/F6) ──────────────────────────────────────────────────
  LIQUIDACION_INVALIDA: 'LIQUIDACION_INVALIDA',
  PERIODO_NO_ABIERTO: 'PERIODO_NO_ABIERTO',
  PERIODO_NO_ENCONTRADO: 'PERIODO_NO_ENCONTRADO',
  PERIODO_YA_LIQUIDADO: 'PERIODO_YA_LIQUIDADO',
  SNAPSHOT_INCOMPLETO: 'SNAPSHOT_INCOMPLETO',

  // ── Liquidación en dos tiempos (L0-L3, plan 2026-08-24) ─────────────────
  // Máquina de estados y guards (L0, 20260830570000)
  LIQUIDACION_ESTADO_INICIAL_INVALIDO: 'LIQUIDACION_ESTADO_INICIAL_INVALIDO',
  LIQUIDACION_TRANSICION_INVALIDA: 'LIQUIDACION_TRANSICION_INVALIDA',
  LIQUIDACION_RESULTADO_INMUTABLE: 'LIQUIDACION_RESULTADO_INMUTABLE',
  LIQUIDACION_REQUIERE_ADMINISTRADOR: 'LIQUIDACION_REQUIERE_ADMINISTRADOR',
  LIQUIDACION_ANULACION_SIN_MOTIVO: 'LIQUIDACION_ANULACION_SIN_MOTIVO',
  // Aplicar (L3, 20260830590000)
  LIQUIDACION_NO_ENCONTRADA: 'LIQUIDACION_NO_ENCONTRADA',
  LIQUIDACION_NO_PENDIENTE: 'LIQUIDACION_NO_PENDIENTE',
  LIQUIDACION_DATOS_CAMBIARON: 'LIQUIDACION_DATOS_CAMBIARON',
  LIQUIDACION_SNAPSHOT_DESACTUALIZADO: 'LIQUIDACION_SNAPSHOT_DESACTUALIZADO',
  LIQUIDACION_PREVUELO_BLOQUEADO: 'LIQUIDACION_PREVUELO_BLOQUEADO',
  // Anular (L6, 20260830630000)
  LIQUIDACION_NO_APLICADA: 'LIQUIDACION_NO_APLICADA',
  LIQUIDACION_CON_PAGOS: 'LIQUIDACION_CON_PAGOS',
  PERIODO_CON_LIQUIDACION_APLICADA: 'PERIODO_CON_LIQUIDACION_APLICADA',

  // ── Cuenta corriente: pagos / intereses (E1-E6) ─────────────────────────
  CARGO_SOBREAPLICADO: 'CARGO_SOBREAPLICADO',
  CUENTA_CORRIENTE_INCOMPLETA: 'CUENTA_CORRIENTE_INCOMPLETA',
  IMPUTACION_INVALIDA: 'IMPUTACION_INVALIDA',
  INMUEBLE_NO_ENCONTRADO: 'INMUEBLE_NO_ENCONTRADO',
  INTERES_INVALIDO: 'INTERES_INVALIDO',
  PAGO_SOBREAPLICADO: 'PAGO_SOBREAPLICADO',
  POLITICA_MORA_NO_CONFIGURADA: 'POLITICA_MORA_NO_CONFIGURADA',
  TENANT_NO_ENCONTRADO: 'TENANT_NO_ENCONTRADO',

  // ── Recaudo: medio de pago y recibo de caja (RC-0..RC-6) ────────────────
  FORMA_PAGO_INVALIDA: 'FORMA_PAGO_INVALIDA',
  PAGO_FECHA_INCOHERENTE: 'PAGO_FECHA_INCOHERENTE',
  PAGO_MEDIO_INCOHERENTE: 'PAGO_MEDIO_INCOHERENTE',
  ANULACION_NO_REVERSABLE: 'ANULACION_NO_REVERSABLE',
  PAGO_ANULACION_SIN_MOTIVO: 'PAGO_ANULACION_SIN_MOTIVO',
  PAGO_MONTO_INVALIDO: 'PAGO_MONTO_INVALIDO',
  PAGO_NO_ENCONTRADO: 'PAGO_NO_ENCONTRADO',
  PAGO_YA_ANULADO: 'PAGO_YA_ANULADO',
  RECIBO_CAJA_NO_ENCONTRADO: 'RECIBO_CAJA_NO_ENCONTRADO',
  RECIBO_CAJA_ENLACE_INVALIDO: 'RECIBO_CAJA_ENLACE_INVALIDO',
  RECIBO_CAJA_VENCIDO: 'RECIBO_CAJA_VENCIDO',
  RECIBO_CAJA_YA_NOTIFICADO: 'RECIBO_CAJA_YA_NOTIFICADO',

  // ── Novedades (E4) ───────────────────────────────────────────────────────
  ADJUSTMENT_ZERO_AMOUNT: 'ADJUSTMENT_ZERO_AMOUNT',
  NOVEDAD_NO_ENCONTRADA: 'NOVEDAD_NO_ENCONTRADA',
  NOVEDAD_NO_PENDIENTE: 'NOVEDAD_NO_PENDIENTE',
  PERIODO_NO_ENCONTRADO_PARA_FECHA_EFECTIVA: 'PERIODO_NO_ENCONTRADO_PARA_FECHA_EFECTIVA',

  // ── Conceptos avanzados Fase 3: novedades.tipo_novedad_id/presupuesto_cuenta_id ──
  TIPO_NOVEDAD_INVALIDO: 'TIPO_NOVEDAD_INVALIDO',
  TIPO_NOVEDAD_TENANT_INCONSISTENTE: 'TIPO_NOVEDAD_TENANT_INCONSISTENTE',

  // ── Conceptos avanzados Fase 4: novedades permanentes/prorrateables ─────
  NOVEDAD_CUOTA_INMUTABLE: 'NOVEDAD_CUOTA_INMUTABLE',
  // Inhabilitar una prorrateable exige saldo pendiente (al menos una cuota
  // sin generar) — distinta de NOVEDAD_NO_PERMANENTE.
  NOVEDAD_NO_INHABILITABLE: 'NOVEDAD_NO_INHABILITABLE',
  NOVEDAD_NO_PERMANENTE: 'NOVEDAD_NO_PERMANENTE',
  // Ya se generaron todas las cuotas de la prorrateable: no hay nada que detener.
  NOVEDAD_SIN_SALDO_PENDIENTE: 'NOVEDAD_SIN_SALDO_PENDIENTE',
  NOVEDAD_YA_INHABILITADA: 'NOVEDAD_YA_INHABILITADA',

  // ── AEL-004 Fase 4: maker-checker de conceptos ──────────────────────────
  CONCEPTO_INMUTABLE: 'CONCEPTO_INMUTABLE',
  SELF_APPROVAL: 'SELF_APPROVAL',

  // ── Ficha de inmueble: documentos (§8.1) ────────────────────────────────
  ARCHIVO_INVALIDO: 'ARCHIVO_INVALIDO',
  TIPO_DOCUMENTO_INVALIDO: 'TIPO_DOCUMENTO_INVALIDO',
  INMUEBLE_INVALIDO: 'INMUEBLE_INVALIDO',

  // ── Terceros: generalización natural/jurídica ───────────────────────────
  TIPO_IDENTIFICACION_INVALIDO: 'TIPO_IDENTIFICACION_INVALIDO',
  ESTADO_TERCERO_INVALIDO: 'ESTADO_TERCERO_INVALIDO',
  TERCERO_REPRESENTANTE_INVALIDO: 'TERCERO_REPRESENTANTE_INVALIDO',
  TERCERO_PAGADOR_INVALIDO: 'TERCERO_PAGADOR_INVALIDO',

  // ── Ficha de copropiedad: datos básicos del tenant ──────────────────────
  TIPO_DIVISION_INVALIDO: 'TIPO_DIVISION_INVALIDO',

  // ── Estado de cuenta (PLAN_DATOS_REALES.md §3.3, D-27/D-28) ──────────────
  ESTADO_CUENTA_NO_ENCONTRADO: 'ESTADO_CUENTA_NO_ENCONTRADO',
  ESTADO_CUENTA_VENCIDO: 'ESTADO_CUENTA_VENCIDO',
  // Enlace público con token HMAC (D-27): firma que no corresponde al id o
  // formato ajeno — distinto de VENCIDO (firma válida, expiración cumplida).
  ESTADO_CUENTA_ENLACE_INVALIDO: 'ESTADO_CUENTA_ENLACE_INVALIDO',
  // Guard anti-doble-envío del correo (D-28): ya existe rastro
  // 'estado_cuenta.enviado' en audit_log dentro de la ventana de dedupe.
  ESTADO_CUENTA_YA_NOTIFICADO: 'ESTADO_CUENTA_YA_NOTIFICADO',

  // ── Motor de Presupuestal / Conceptos ────────────────────────────────
  // Tope legal de intereses (Art. 30 Ley 675): la tasa de mora no puede
  // superar la bancario corriente certificada por la Superfinanciera.
  TOPE_LEGAL_NO_DECLARADO: 'TOPE_LEGAL_NO_DECLARADO',
  // Protección de conceptos de plantilla: impide modificar conceptos que
  // provienen de la semilla del sistema (is_plantilla = true).
  CONCEPTO_NOVEDAD_PROTEGIDO: 'CONCEPTO_NOVEDAD_PROTEGIDO',

  // ── Motor de Gestión de Cartera (CAR §7-§8) ──────────────────────────────
  PERIODO_SIN_FECHA_VENCIMIENTO: 'PERIODO_SIN_FECHA_VENCIMIENTO',
  POLITICA_CLASIFICACION_SIN_TRAMOS: 'POLITICA_CLASIFICACION_SIN_TRAMOS',
  POLITICA_CLASIFICACION_CODIGO_DUPLICADO: 'POLITICA_CLASIFICACION_CODIGO_DUPLICADO',
  POLITICA_CLASIFICACION_SIN_TRAMO_INICIAL: 'POLITICA_CLASIFICACION_SIN_TRAMO_INICIAL',
  POLITICA_CLASIFICACION_SIN_TRAMO_ABIERTO: 'POLITICA_CLASIFICACION_SIN_TRAMO_ABIERTO',
  POLITICA_CLASIFICACION_HUECO: 'POLITICA_CLASIFICACION_HUECO',
  POLITICA_CLASIFICACION_HUECO_O_SOLAPE: 'POLITICA_CLASIFICACION_HUECO_O_SOLAPE',
  POLITICA_CLASIFICACION_NO_VIGENTE: 'POLITICA_CLASIFICACION_NO_VIGENTE',
  TRAMO_CLASIFICACION_NO_ENCONTRADO: 'TRAMO_CLASIFICACION_NO_ENCONTRADO',
  SNAPSHOT_NO_DISPONIBLE: 'SNAPSHOT_NO_DISPONIBLE',
  TASA_REFERENCIA_NO_ENCONTRADA: 'TASA_REFERENCIA_NO_ENCONTRADA',
  INTERES_EXCEDE_TOPE_LEGAL: 'INTERES_EXCEDE_TOPE_LEGAL',
  ESTRATEGIA_COBRANZA_TRAMO_AJENO: 'ESTRATEGIA_COBRANZA_TRAMO_AJENO',
  ACCION_COBRANZA_CONTEXTO_INMUTABLE: 'ACCION_COBRANZA_CONTEXTO_INMUTABLE',
  ACCION_COBRANZA_ESTADO_INICIAL_INVALIDO: 'ACCION_COBRANZA_ESTADO_INICIAL_INVALIDO',
  ACCION_COBRANZA_TRANSICION_INVALIDA: 'ACCION_COBRANZA_TRANSICION_INVALIDA',
  ACCION_COBRANZA_REQUIERE_ADMINISTRADOR: 'ACCION_COBRANZA_REQUIERE_ADMINISTRADOR',
  ACCION_COBRANZA_AUTOAPROBACION: 'ACCION_COBRANZA_AUTOAPROBACION',
  ACCION_COBRANZA_NO_ENCONTRADA: 'ACCION_COBRANZA_NO_ENCONTRADA',
  ACCION_COBRANZA_CANAL_NO_SOPORTADO: 'ACCION_COBRANZA_CANAL_NO_SOPORTADO',
  ACCION_COBRANZA_ESTADO_NO_EJECUTABLE: 'ACCION_COBRANZA_ESTADO_NO_EJECUTABLE',
  ACCION_COBRANZA_SIN_PLANTILLA: 'ACCION_COBRANZA_SIN_PLANTILLA',
  ACCION_COBRANZA_EVENTO_NO_SOPORTADO: 'ACCION_COBRANZA_EVENTO_NO_SOPORTADO',
  ACCION_COBRANZA_DESTINATARIO_SIN_TELEFONO: 'ACCION_COBRANZA_DESTINATARIO_SIN_TELEFONO',

  // ── Cartera: evidencia jurídica y trazabilidad (CJ-*, PRQ-CAR-022) ───────
  // Prescripción, transferencias de propiedad, legal hold, procedencia de
  // contacto, envío de documentos y costas judiciales — bitácoras factuales
  // auditadas 2026-08-29 (VALUACION CAR_10, PROMPT-CAR-JUR-001).
  ACTUACION_INVALIDA: 'ACTUACION_INVALIDA',
  // CJ-4 §11.3: la plantilla contiene una afirmación jurídica prohibida.
  CONTENIDO_PROHIBIDO: 'CONTENIDO_PROHIBIDO',
  ENVIO_INVALIDO: 'ENVIO_INVALIDO',
  ENVIO_NO_ENCONTRADO: 'ENVIO_NO_ENCONTRADO',
  LEGAL_HOLD_NO_ENCONTRADO: 'LEGAL_HOLD_NO_ENCONTRADO',
  // Legal hold (CJ-3 §10.6): distinto de FONDO_MOTIVO_REQUERIDO/SOLICITUD_MOTIVO_REQUERIDO.
  MOTIVO_REQUERIDO: 'MOTIVO_REQUERIDO',
  // Procedencia del dato de contacto de un tercero (CJ-9): origen_id no
  // pertenece al catálogo ORIGEN_CONTACTO_TERCERO.
  ORIGEN_INVALIDO: 'ORIGEN_INVALIDO',
  // Nueva versión de una política de clasificación (§8.5): el origen no
  // existe o no es visible para este tenant.
  POLITICA_INVALIDA: 'POLITICA_INVALIDA',
  PROPIETARIO_ANTERIOR_INVALIDO: 'PROPIETARIO_ANTERIOR_INVALIDO',
  PROPIETARIO_NUEVO_INVALIDO: 'PROPIETARIO_NUEVO_INVALIDO',
  TIPO_ACTO_INVALIDO: 'TIPO_ACTO_INVALIDO',
  TIPO_TRANSFERENCIA_INVALIDO: 'TIPO_TRANSFERENCIA_INVALIDO',

  // ── Promesas y acuerdos de pago (F5) ────────────────────────────────────
  PROMESA_TRANSICION_INVALIDA: 'PROMESA_TRANSICION_INVALIDA',
  ACUERDO_ESTADO_INICIAL_INVALIDO: 'ACUERDO_ESTADO_INICIAL_INVALIDO',
  ACUERDO_TRANSICION_INVALIDA: 'ACUERDO_TRANSICION_INVALIDA',
  ACUERDO_REQUIERE_ADMINISTRADOR: 'ACUERDO_REQUIERE_ADMINISTRADOR',
  ACUERDO_AUTOAPROBACION: 'ACUERDO_AUTOAPROBACION',
  // registrar-pago: el pago no puede conciliarse contra la cuota del acuerdo.
  CUOTA_ACUERDO_NO_CONCILIABLE: 'CUOTA_ACUERDO_NO_CONCILIABLE',
  CUOTA_ACUERDO_INVALIDA: 'CUOTA_ACUERDO_INVALIDA',
  CUOTA_ACUERDO_TRANSICION_INVALIDA: 'CUOTA_ACUERDO_TRANSICION_INVALIDA',

  // ── Escalamiento (F6) ────────────────────────────────────────────────
  CARTERA_ETAPA_INICIAL_INVALIDA: 'CARTERA_ETAPA_INICIAL_INVALIDA',
  CARTERA_ETAPA_CONTEXTO_INMUTABLE: 'CARTERA_ETAPA_CONTEXTO_INMUTABLE',
  CARTERA_ETAPA_CONGELADA: 'CARTERA_ETAPA_CONGELADA',
  CARTERA_ETAPA_TRANSICION_INVALIDA: 'CARTERA_ETAPA_TRANSICION_INVALIDA',
  CARTERA_ETAPA_SIN_PROPUESTA: 'CARTERA_ETAPA_SIN_PROPUESTA',
  CARTERA_ETAPA_REQUIERE_ADMINISTRADOR: 'CARTERA_ETAPA_REQUIERE_ADMINISTRADOR',
  CARTERA_ETAPA_AUTOAPROBACION: 'CARTERA_ETAPA_AUTOAPROBACION',

  // ── Jurídico (F7) ────────────────────────────────────────────────────
  CERTIFICACION_REQUIERE_ADMINISTRADOR: 'CERTIFICACION_REQUIERE_ADMINISTRADOR',
  CERTIFICACION_INMUTABLE: 'CERTIFICACION_INMUTABLE',
  CERTIFICACION_TRANSICION_INVALIDA: 'CERTIFICACION_TRANSICION_INVALIDA',
  CERTIFICACION_ANULACION_SIN_MOTIVO: 'CERTIFICACION_ANULACION_SIN_MOTIVO',
  CERTIFICACION_SIN_DEUDA: 'CERTIFICACION_SIN_DEUDA',
  CERTIFICACION_SIN_POLITICA_VIGENTE: 'CERTIFICACION_SIN_POLITICA_VIGENTE',
  CASO_JURIDICO_REQUIERE_ADMINISTRADOR: 'CASO_JURIDICO_REQUIERE_ADMINISTRADOR',
  CASO_JURIDICO_CERTIFICACION_INVALIDA: 'CASO_JURIDICO_CERTIFICACION_INVALIDA',
  CASO_JURIDICO_ABOGADO_INVALIDO: 'CASO_JURIDICO_ABOGADO_INVALIDO',
  CASO_JURIDICO_CONTEXTO_INMUTABLE: 'CASO_JURIDICO_CONTEXTO_INMUTABLE',
  CASO_JURIDICO_CIERRE_REQUIERE_ADMINISTRADOR: 'CASO_JURIDICO_CIERRE_REQUIERE_ADMINISTRADOR',
  CASO_JURIDICO_INVALIDO: 'CASO_JURIDICO_INVALIDO',
  CASO_JURIDICO_NO_ENCONTRADO: 'CASO_JURIDICO_NO_ENCONTRADO',
  COSTA_JUDICIAL_INMUTABLE: 'COSTA_JUDICIAL_INMUTABLE',

  // ── Plantillas SMS ────────────────────────────────────────────────────
  SMS_UNKNOWN_EVENT: 'SMS_UNKNOWN_EVENT',
  SMS_BODY_TOO_LONG: 'SMS_BODY_TOO_LONG',
  SMS_UNKNOWN_FIELDS: 'SMS_UNKNOWN_FIELDS',
  SMS_INVALID_PHONE: 'SMS_INVALID_PHONE',
  SMS_TEMPLATE_NOT_FOUND: 'SMS_TEMPLATE_NOT_FOUND',
  SMS_EVENT_NOT_ACTIVE: 'SMS_EVENT_NOT_ACTIVE',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',

  // ── Plantillas de correo (Brevo templates) ─────────────────────────────
  EMAIL_UNKNOWN_EVENT: 'EMAIL_UNKNOWN_EVENT',
  EMAIL_BODY_TOO_SHORT: 'EMAIL_BODY_TOO_SHORT',
  EMAIL_UNKNOWN_FIELDS: 'EMAIL_UNKNOWN_FIELDS',
  EMAIL_MISSING_PARAMS_PREFIX: 'EMAIL_MISSING_PARAMS_PREFIX',
  EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',

  // ── enviar-correo-compositor: envío real vía Brevo ──────────────────────
  // La API de Brevo respondió con error al intentar enviar el correo.
  BREVO_ERROR: 'BREVO_ERROR',
  COMPOSITOR_DESACTIVADO: 'COMPOSITOR_DESACTIVADO',
  // Faltan variables de entorno de Brevo (API key o remitente).
  CONFIG_INCOMPLETA: 'CONFIG_INCOMPLETA',
  PLANTILLA_DESACTIVADA: 'PLANTILLA_DESACTIVADA',
  PLANTILLA_NO_ENCONTRADA: 'PLANTILLA_NO_ENCONTRADA',

  // ── Fuente de financiación (20260830210000, lista_tipos) ────────────────
  FUENTE_FINANCIACION_TIPO_SIN_MAPEO: 'FUENTE_FINANCIACION_TIPO_SIN_MAPEO',
  TIPO_FUENTE_INEXISTENTE: 'TIPO_FUENTE_INEXISTENTE',
  TIPO_FUENTE_INVALIDO: 'TIPO_FUENTE_INVALIDO',
  TIPO_FUENTE_TENANT_INCONSISTENTE: 'TIPO_FUENTE_TENANT_INCONSISTENTE',

  // ── Agrupaciones de predios (20260830250000) ─────────────────────────────
  AGRUPACION_INEXISTENTE: 'AGRUPACION_INEXISTENTE',
  AGRUPACION_TIPO_INVALIDO: 'AGRUPACION_TIPO_INVALIDO',
  AGRUPACION_TIPO_TENANT_INCONSISTENTE: 'AGRUPACION_TIPO_TENANT_INCONSISTENTE',
  AGRUPACION_TIPO_INACTIVO: 'AGRUPACION_TIPO_INACTIVO',
  AGRUPACION_CICLO: 'AGRUPACION_CICLO',
  AGRUPACION_PADRE_INEXISTENTE: 'AGRUPACION_PADRE_INEXISTENTE',
  AGRUPACION_TENANT_INCONSISTENTE: 'AGRUPACION_TENANT_INCONSISTENTE',
  AGRUPACION_PROFUNDIDAD_MAXIMA: 'AGRUPACION_PROFUNDIDAD_MAXIMA',

  // ── Centro de costo en presupuesto (20260830420000) ──────────────────────
  CENTRO_COSTO_INEXISTENTE: 'CENTRO_COSTO_INEXISTENTE',
  CENTRO_COSTO_INVALIDO: 'CENTRO_COSTO_INVALIDO',
  CENTRO_COSTO_TENANT_INCONSISTENTE: 'CENTRO_COSTO_TENANT_INCONSISTENTE',
  CENTRO_COSTO_INACTIVO: 'CENTRO_COSTO_INACTIVO',

  // ── Comprobante de pago adjunto (20260903170000) ─────────────────────────
  PAGO_INVALIDO: 'PAGO_INVALIDO',

  // ── Pasarelas de pago (20260904100000, fase de estructura) ───────────────
  PASARELA_NO_CONFIGURADA: 'PASARELA_NO_CONFIGURADA',
  PASARELA_CREDENCIAL_INVALIDA: 'PASARELA_CREDENCIAL_INVALIDA',
  PASARELA_CREDENCIAL_FALTANTE: 'PASARELA_CREDENCIAL_FALTANTE',
  PASARELA_NO_VERIFICADA: 'PASARELA_NO_VERIFICADA',
  PASARELA_PROVEEDOR_NO_IMPLEMENTADO: 'PASARELA_PROVEEDOR_NO_IMPLEMENTADO',

  // ── Intenciones de pago por pasarela (20260904130000, fase 2) ────────────
  INTENCION_NO_PENDIENTE: 'INTENCION_NO_PENDIENTE',
  INTENCION_TERMINAL: 'INTENCION_TERMINAL',
  INTENCION_TRANSICION_INVALIDA: 'INTENCION_TRANSICION_INVALIDA',

  // ── Cobro real por pasarela: crear-intencion-pago / webhook-pasarela
  //    (fase 2, integración Wompi) ─────────────────────────────────────────
  PASARELA_MONTO_EXCEDE_SALDO: 'PASARELA_MONTO_EXCEDE_SALDO',
  PASARELA_WEBHOOK_TOKEN_INVALIDO: 'PASARELA_WEBHOOK_TOKEN_INVALIDO',
  PASARELA_WEBHOOK_FIRMA_INVALIDA: 'PASARELA_WEBHOOK_FIRMA_INVALIDA',
  PASARELA_TRANSACCION_NO_ENCONTRADA: 'PASARELA_TRANSACCION_NO_ENCONTRADA',
  PASARELA_INTENCION_NO_ENCONTRADA: 'PASARELA_INTENCION_NO_ENCONTRADA',
  PASARELA_RESPUESTA_INVALIDA: 'PASARELA_RESPUESTA_INVALIDA',

  // ── Conciliación bancaria (20260904170000, Fase 3 Bloque B) ──────────────
  CONCILIACION_ARCHIVO_NO_RECONOCIDO: 'CONCILIACION_ARCHIVO_NO_RECONOCIDO',
  CONCILIACION_LINEA_YA_RESUELTA: 'CONCILIACION_LINEA_YA_RESUELTA',
  CONCILIACION_DESCARTE_SIN_MOTIVO: 'CONCILIACION_DESCARTE_SIN_MOTIVO',

  // ── Cartera: cron diario, webhook de acuses, siembra de configuración
  //    (CAR §18/§34, bloques 1-2 y 4) ────────────────────────────────────
  CARTERA_CONFIGURACION_YA_EXISTE: 'CARTERA_CONFIGURACION_YA_EXISTE',
  CRON_TOKEN_INVALIDO: 'CRON_TOKEN_INVALIDO',
  WEBHOOK_TOKEN_INVALIDO: 'WEBHOOK_TOKEN_INVALIDO',

  // ── Auditoría interna (20260915100000, PROMPT AUDITORÍA §34, §70) ────────
  HALLAZGO_NO_ENCONTRADO: 'HALLAZGO_NO_ENCONTRADO',
  EVIDENCIA_DUPLICADA: 'EVIDENCIA_DUPLICADA',
} as const satisfies Record<string, string>

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
