/**
 * Registro central de códigos de error (Doc 14 — cierra el gap de
 * auditoría del corpus 01-24: sin esto, los ~35+ códigos existentes solo
 * vivían como convención textual dispersa entre SQL (`raise exception
 * 'CODIGO: mensaje'`) y TS (`errorResponse(status, 'CODIGO', ...)`),
 * verificable solo por grep, nunca por el compilador ni por un test.
 *
 * Sin dependencias runtime — importable tanto desde paquetes Node
 * (vía dist/) como directo desde Deno (Edge Functions), igual que
 * database.generated.ts.
 *
 * AD-35 (Doc 14, mitad "versionado"): sin versionado de API en v0 — un
 * único cliente propietario (apps/web) desplegado junto a las Edge
 * Functions; se adopta cuando exista un segundo consumidor externo real
 * (AD-23). Un código de error que cambia de semántica se retira (nunca se
 * reutiliza el nombre) y se añade uno nuevo — no hace falta un esquema de
 * versión aparte mientras el único consumidor se despliega en el mismo
 * commit que el servidor.
 *
 * tests/governance/error-codes-coverage.test.ts escanea `supabase/` y
 * falla si aparece un código nuevo que no esté aquí — mantener esta lista
 * al día no es opcional, es lo que el test verifica.
 *
 * GENERADO A MANO, no por introspección — a diferencia de
 * database.generated.ts, no hay una fuente única de verdad estructural
 * para extraer esto (los códigos viven en strings SQL y TS). Regenerar
 * manualmente si el test-guardia falla.
 */

export const ERROR_CODES = {
  // ── Transversal (rate limiting, contrato HTTP, autenticación) ─────────
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // ── Tenancy / membresías / invitaciones (Fase I) ───────────────────────
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INVITE_PENDING: 'INVITE_PENDING',
  INV_EMAIL_MISMATCH: 'INV_EMAIL_MISMATCH',
  INV_EXPIRED: 'INV_EXPIRED',
  INV_NOT_FOUND: 'INV_NOT_FOUND',
  INV_NOT_PENDING: 'INV_NOT_PENDING',
  INV_USED: 'INV_USED',
  LAST_AGENT: 'LAST_AGENT',
  MEMBERSHIP_FETCH_FAILED: 'MEMBERSHIP_FETCH_FAILED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  NO_MEMBERSHIP: 'NO_MEMBERSHIP',
  PRIVILEGE_ESCALATION: 'PRIVILEGE_ESCALATION',
  SELF_MODIFY: 'SELF_MODIFY',
  SLUG_INVALID: 'SLUG_INVALID',
  SLUG_TAKEN: 'SLUG_TAKEN',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',

  // ── Guards de dominio genéricos ─────────────────────────────────────────
  APPEND_ONLY: 'APPEND_ONLY',
  INVALID_INSERT: 'INVALID_INSERT',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_UPDATE: 'INVALID_UPDATE',

  // ── Motor Presupuestal (GAP-19) ─────────────────────────────────────────
  BUDGET_NOT_RECONCILED: 'BUDGET_NOT_RECONCILED',
  COEFICIENTE_SET_NO_VIGENTE: 'COEFICIENTE_SET_NO_VIGENTE',
  DISTRIBUCION_INVALIDA: 'DISTRIBUCION_INVALIDA',
  FINANCIACION_EXCEDE_PRESUPUESTO: 'FINANCIACION_EXCEDE_PRESUPUESTO',
  FONDO_IMPREVISTOS_NO_EXISTE: 'FONDO_IMPREVISTOS_NO_EXISTE',
  FONDO_INSUFICIENTE: 'FONDO_INSUFICIENTE',
  IMMUTABLE_BUDGET: 'IMMUTABLE_BUDGET',
  IMMUTABLE_COEFFICIENT_SET: 'IMMUTABLE_COEFFICIENT_SET',
  IMMUTABLE_POLICY: 'IMMUTABLE_POLICY',
  NECESIDAD_NEGATIVA: 'NECESIDAD_NEGATIVA',
  POLITICA_NO_VIGENTE: 'POLITICA_NO_VIGENTE',
  PRESUPUESTO_NO_ENCONTRADO: 'PRESUPUESTO_NO_ENCONTRADO',
  SIN_COEFICIENTE: 'SIN_COEFICIENTE',
  SIN_INMUEBLES: 'SIN_INMUEBLES',

  // ── Árbol de cuentas presupuestales (E8) ─────────────────────────────────
  CUENTA_INEXISTENTE: 'CUENTA_INEXISTENTE',
  CUENTA_PADRE_INEXISTENTE: 'CUENTA_PADRE_INEXISTENTE',
  CUENTA_TENANT_INCONSISTENTE: 'CUENTA_TENANT_INCONSISTENTE',
  CUENTA_NO_ES_HOJA: 'CUENTA_NO_ES_HOJA',
  CUENTA_NATURALEZA_MEZCLADA: 'CUENTA_NATURALEZA_MEZCLADA',
  CUENTA_NATURALEZA_INVALIDA: 'CUENTA_NATURALEZA_INVALIDA',
  CUENTA_PROFUNDIDAD_MAXIMA: 'CUENTA_PROFUNDIDAD_MAXIMA',
  CUENTA_PROFUNDIDAD_EXCEDIDA: 'CUENTA_PROFUNDIDAD_EXCEDIDA',
  CUENTA_CICLO: 'CUENTA_CICLO',
  CUENTA_TIENE_CONCEPTO: 'CUENTA_TIENE_CONCEPTO',
  CONCEPTO_INEXISTENTE: 'CONCEPTO_INEXISTENTE',
  CONCEPTO_TENANT_INCONSISTENTE: 'CONCEPTO_TENANT_INCONSISTENTE',

  // ── Plan de cuentas contable (PC-1) ──────────────────────────────────────
  // Catálogo distinto del presupuestal: aquí la jerarquía la impone el propio código numérico
  // (5505 cuelga de 55, que cuelga de 5), no un parent_id libre — de ahí que los códigos de
  // error hablen de niveles y prefijos y no de hojas ni de naturaleza mezclada.
  CUENTA_RAIZ_INVALIDA: 'CUENTA_RAIZ_INVALIDA',
  CUENTA_LONGITUD_INVALIDA: 'CUENTA_LONGITUD_INVALIDA',
  CUENTA_NIVEL_SALTADO: 'CUENTA_NIVEL_SALTADO',
  CUENTA_CODIGO_INCOHERENTE: 'CUENTA_CODIGO_INCOHERENTE',
  CUENTA_AGRUPA_SUBCUENTAS: 'CUENTA_AGRUPA_SUBCUENTAS',
  // Instanciación del plan por copropiedad (fn_instanciar_plan_contable, PC-2)
  PLAN_CONTABLE_INEXISTENTE: 'PLAN_CONTABLE_INEXISTENTE',
  TENANT_INEXISTENTE: 'TENANT_INEXISTENTE',

  // ── Puentes hacia el plan contable (PC-3) ────────────────────────────────
  // Los emite validar_cuenta_contable_destino(), compartida por presupuesto_cuenta,
  // fondos, cuentas_bancarias y contable_cuenta_default.
  CUENTA_CONTABLE_INEXISTENTE: 'CUENTA_CONTABLE_INEXISTENTE',
  CUENTA_CONTABLE_TENANT_INCONSISTENTE: 'CUENTA_CONTABLE_TENANT_INCONSISTENTE',
  CUENTA_CONTABLE_NO_ADMITE_MOVIMIENTO: 'CUENTA_CONTABLE_NO_ADMITE_MOVIMIENTO',
  CUENTA_CONTABLE_INACTIVA: 'CUENTA_CONTABLE_INACTIVA',
  CUENTA_CONTABLE_CLASE_INCOMPATIBLE: 'CUENTA_CONTABLE_CLASE_INCOMPATIBLE',
  EVENTO_CONTABLE_INVALIDO: 'EVENTO_CONTABLE_INVALIDO',
  // Hace cumplir en el motor una decisión de diseño ya fundamentada (PC-9): impide recrear por
  // tenant un código de cuenta que la plantilla global retiró por doctrina (ej. grupo 27/32).
  CUENTA_CODIGO_RETIRADO: 'CUENTA_CODIGO_RETIRADO',

  // ── Contrapartida de la ejecución presupuestal (PC-4) ────────────────────
  // Sin contrapartida el movimiento tiene débito y ningún crédito: no es exportable.
  LIQUIDACION_REQUERIDA: 'LIQUIDACION_REQUERIDA',
  LIQUIDACION_CUENTA_BANCARIA_REQUERIDA: 'LIQUIDACION_CUENTA_BANCARIA_REQUERIDA',
  LIQUIDACION_CUENTA_BANCARIA_NO_APLICA: 'LIQUIDACION_CUENTA_BANCARIA_NO_APLICA',
  LIQUIDACION_TERCERO_REQUERIDO: 'LIQUIDACION_TERCERO_REQUERIDO',
  CUENTA_BANCARIA_INEXISTENTE: 'CUENTA_BANCARIA_INEXISTENTE',
  CUENTA_BANCARIA_TENANT_INCONSISTENTE: 'CUENTA_BANCARIA_TENANT_INCONSISTENTE',
  CUENTA_BANCARIA_INACTIVA: 'CUENTA_BANCARIA_INACTIVA',
  TERCERO_INEXISTENTE: 'TERCERO_INEXISTENTE',
  TERCERO_TENANT_INCONSISTENTE: 'TERCERO_TENANT_INCONSISTENTE',
  FECHA_DOCUMENTO_FUERA_DE_EJERCICIO: 'FECHA_DOCUMENTO_FUERA_DE_EJERCICIO',

  // ── Ejecución presupuestal (E9) ──────────────────────────────────────────
  PERIODO_INEXISTENTE: 'PERIODO_INEXISTENTE',
  PERIODO_TENANT_INCONSISTENTE: 'PERIODO_TENANT_INCONSISTENTE',
  CUENTA_CONCEPTO_AUTOMATICO: 'CUENTA_CONCEPTO_AUTOMATICO',
  REVERSION_SIN_ORIGEN: 'REVERSION_SIN_ORIGEN',
  REVERSION_CUENTA_DISTINTA: 'REVERSION_CUENTA_DISTINTA',
  MOVIMIENTO_INEXISTENTE: 'MOVIMIENTO_INEXISTENTE',
  MOVIMIENTO_TENANT_INCONSISTENTE: 'MOVIMIENTO_TENANT_INCONSISTENTE',

  // ── Liquidación (F5/F6) ──────────────────────────────────────────────────
  LIQUIDACION_INVALIDA: 'LIQUIDACION_INVALIDA',
  PERIODO_NO_ABIERTO: 'PERIODO_NO_ABIERTO',
  PERIODO_NO_ENCONTRADO: 'PERIODO_NO_ENCONTRADO',
  PERIODO_YA_LIQUIDADO: 'PERIODO_YA_LIQUIDADO',
  SNAPSHOT_INCOMPLETO: 'SNAPSHOT_INCOMPLETO',

  // ── Liquidación en dos tiempos (L0-L3, plan 2026-08-24) ─────────────────
  // Máquina de estados y guards (L0, 20260830570000)
  LIQUIDACION_ESTADO_INICIAL_INVALIDO: 'LIQUIDACION_ESTADO_INICIAL_INVALIDO',
  LIQUIDACION_TRANSICION_INVALIDA: 'LIQUIDACION_TRANSICION_INVALIDA',
  LIQUIDACION_RESULTADO_INMUTABLE: 'LIQUIDACION_RESULTADO_INMUTABLE',
  LIQUIDACION_REQUIERE_ADMINISTRADOR: 'LIQUIDACION_REQUIERE_ADMINISTRADOR',
  LIQUIDACION_ANULACION_SIN_MOTIVO: 'LIQUIDACION_ANULACION_SIN_MOTIVO',
  // Aplicar (L3, 20260830590000)
  LIQUIDACION_NO_ENCONTRADA: 'LIQUIDACION_NO_ENCONTRADA',
  LIQUIDACION_NO_PENDIENTE: 'LIQUIDACION_NO_PENDIENTE',
  LIQUIDACION_DATOS_CAMBIARON: 'LIQUIDACION_DATOS_CAMBIARON',
  LIQUIDACION_SNAPSHOT_DESACTUALIZADO: 'LIQUIDACION_SNAPSHOT_DESACTUALIZADO',
  LIQUIDACION_PREVUELO_BLOQUEADO: 'LIQUIDACION_PREVUELO_BLOQUEADO',
  // Anular (L6, 20260830630000)
  LIQUIDACION_NO_APLICADA: 'LIQUIDACION_NO_APLICADA',
  LIQUIDACION_CON_PAGOS: 'LIQUIDACION_CON_PAGOS',
  PERIODO_CON_LIQUIDACION_APLICADA: 'PERIODO_CON_LIQUIDACION_APLICADA',

  // ── Cuenta corriente: pagos / intereses (E1-E6) ─────────────────────────
  CARGO_SOBREAPLICADO: 'CARGO_SOBREAPLICADO',
  CUENTA_CORRIENTE_INCOMPLETA: 'CUENTA_CORRIENTE_INCOMPLETA',
  IMPUTACION_INVALIDA: 'IMPUTACION_INVALIDA',
  INMUEBLE_NO_ENCONTRADO: 'INMUEBLE_NO_ENCONTRADO',
  INTERES_INVALIDO: 'INTERES_INVALIDO',
  PAGO_SOBREAPLICADO: 'PAGO_SOBREAPLICADO',
  POLITICA_MORA_NO_CONFIGURADA: 'POLITICA_MORA_NO_CONFIGURADA',
  TENANT_NO_ENCONTRADO: 'TENANT_NO_ENCONTRADO',

  // ── Novedades (E4) ───────────────────────────────────────────────────────
  ADJUSTMENT_ZERO_AMOUNT: 'ADJUSTMENT_ZERO_AMOUNT',
  NOVEDAD_NO_ENCONTRADA: 'NOVEDAD_NO_ENCONTRADA',
  NOVEDAD_NO_PENDIENTE: 'NOVEDAD_NO_PENDIENTE',
  PERIODO_NO_ENCONTRADO_PARA_FECHA_EFECTIVA: 'PERIODO_NO_ENCONTRADO_PARA_FECHA_EFECTIVA',

  // ── Conceptos avanzados Fase 3: novedades.tipo_novedad_id/presupuesto_cuenta_id ──
  TIPO_NOVEDAD_INVALIDO: 'TIPO_NOVEDAD_INVALIDO',
  TIPO_NOVEDAD_TENANT_INCONSISTENTE: 'TIPO_NOVEDAD_TENANT_INCONSISTENTE',

  // ── Conceptos avanzados Fase 4: novedades permanentes/prorrateables ─────
  NOVEDAD_NO_PERMANENTE: 'NOVEDAD_NO_PERMANENTE',
  NOVEDAD_YA_INHABILITADA: 'NOVEDAD_YA_INHABILITADA',
  NOVEDAD_CUOTA_INMUTABLE: 'NOVEDAD_CUOTA_INMUTABLE',

  // ── AEL-004 Fase 4: maker-checker de conceptos ──────────────────────────
  CONCEPTO_INMUTABLE: 'CONCEPTO_INMUTABLE',
  SELF_APPROVAL: 'SELF_APPROVAL',

  // ── Ficha de inmueble: documentos (§8.1) ────────────────────────────────
  ARCHIVO_INVALIDO: 'ARCHIVO_INVALIDO',
  TIPO_DOCUMENTO_INVALIDO: 'TIPO_DOCUMENTO_INVALIDO',
  INMUEBLE_INVALIDO: 'INMUEBLE_INVALIDO',

  // ── Terceros: generalización natural/jurídica ───────────────────────────
  TIPO_IDENTIFICACION_INVALIDO: 'TIPO_IDENTIFICACION_INVALIDO',
  ESTADO_TERCERO_INVALIDO: 'ESTADO_TERCERO_INVALIDO',
  TERCERO_REPRESENTANTE_INVALIDO: 'TERCERO_REPRESENTANTE_INVALIDO',
  TERCERO_PAGADOR_INVALIDO: 'TERCERO_PAGADOR_INVALIDO',

  // ── Ficha de copropiedad: datos básicos del tenant ──────────────────────
  TIPO_DIVISION_INVALIDO: 'TIPO_DIVISION_INVALIDO',

  // ── Estado de cuenta (PLAN_DATOS_REALES.md §3.3, D-27/D-28) ──────────────
  ESTADO_CUENTA_NO_ENCONTRADO: 'ESTADO_CUENTA_NO_ENCONTRADO',
  ESTADO_CUENTA_VENCIDO: 'ESTADO_CUENTA_VENCIDO',
  // Enlace público con token HMAC (D-27): firma que no corresponde al id o
  // formato ajeno — distinto de VENCIDO (firma válida, expiración cumplida).
  ESTADO_CUENTA_ENLACE_INVALIDO: 'ESTADO_CUENTA_ENLACE_INVALIDO',
  // Guard anti-doble-envío del correo (D-28): ya existe rastro
  // 'estado_cuenta.enviado' en audit_log dentro de la ventana de dedupe.
  ESTADO_CUENTA_YA_NOTIFICADO: 'ESTADO_CUENTA_YA_NOTIFICADO',

  // ── Motor de Gestión de Cartera (CAR §7-§8) ──────────────────────────────
  PERIODO_SIN_FECHA_VENCIMIENTO: 'PERIODO_SIN_FECHA_VENCIMIENTO',
  POLITICA_CLASIFICACION_SIN_TRAMOS: 'POLITICA_CLASIFICACION_SIN_TRAMOS',
  POLITICA_CLASIFICACION_CODIGO_DUPLICADO: 'POLITICA_CLASIFICACION_CODIGO_DUPLICADO',
  POLITICA_CLASIFICACION_SIN_TRAMO_INICIAL: 'POLITICA_CLASIFICACION_SIN_TRAMO_INICIAL',
  POLITICA_CLASIFICACION_SIN_TRAMO_ABIERTO: 'POLITICA_CLASIFICACION_SIN_TRAMO_ABIERTO',
  POLITICA_CLASIFICACION_HUECO: 'POLITICA_CLASIFICACION_HUECO',
  POLITICA_CLASIFICACION_HUECO_O_SOLAPE: 'POLITICA_CLASIFICACION_HUECO_O_SOLAPE',
  POLITICA_CLASIFICACION_NO_VIGENTE: 'POLITICA_CLASIFICACION_NO_VIGENTE',
  TRAMO_CLASIFICACION_NO_ENCONTRADO: 'TRAMO_CLASIFICACION_NO_ENCONTRADO',
  SNAPSHOT_NO_DISPONIBLE: 'SNAPSHOT_NO_DISPONIBLE',
  TASA_REFERENCIA_NO_ENCONTRADA: 'TASA_REFERENCIA_NO_ENCONTRADA',
  INTERES_EXCEDE_TOPE_LEGAL: 'INTERES_EXCEDE_TOPE_LEGAL',
  ESTRATEGIA_COBRANZA_TRAMO_AJENO: 'ESTRATEGIA_COBRANZA_TRAMO_AJENO',
  ACCION_COBRANZA_CONTEXTO_INMUTABLE: 'ACCION_COBRANZA_CONTEXTO_INMUTABLE',
  ACCION_COBRANZA_ESTADO_INICIAL_INVALIDO: 'ACCION_COBRANZA_ESTADO_INICIAL_INVALIDO',
  ACCION_COBRANZA_TRANSICION_INVALIDA: 'ACCION_COBRANZA_TRANSICION_INVALIDA',
  ACCION_COBRANZA_REQUIERE_ADMINISTRADOR: 'ACCION_COBRANZA_REQUIERE_ADMINISTRADOR',
  ACCION_COBRANZA_AUTOAPROBACION: 'ACCION_COBRANZA_AUTOAPROBACION',
  ACCION_COBRANZA_NO_ENCONTRADA: 'ACCION_COBRANZA_NO_ENCONTRADA',
  ACCION_COBRANZA_CANAL_NO_SOPORTADO: 'ACCION_COBRANZA_CANAL_NO_SOPORTADO',
  ACCION_COBRANZA_ESTADO_NO_EJECUTABLE: 'ACCION_COBRANZA_ESTADO_NO_EJECUTABLE',
  ACCION_COBRANZA_SIN_PLANTILLA: 'ACCION_COBRANZA_SIN_PLANTILLA',
  ACCION_COBRANZA_EVENTO_NO_SOPORTADO: 'ACCION_COBRANZA_EVENTO_NO_SOPORTADO',
  ACCION_COBRANZA_DESTINATARIO_SIN_TELEFONO: 'ACCION_COBRANZA_DESTINATARIO_SIN_TELEFONO',

  // ── Promesas y acuerdos de pago (F5) ────────────────────────────────────
  PROMESA_TRANSICION_INVALIDA: 'PROMESA_TRANSICION_INVALIDA',
  ACUERDO_ESTADO_INICIAL_INVALIDO: 'ACUERDO_ESTADO_INICIAL_INVALIDO',
  ACUERDO_TRANSICION_INVALIDA: 'ACUERDO_TRANSICION_INVALIDA',
  ACUERDO_REQUIERE_ADMINISTRADOR: 'ACUERDO_REQUIERE_ADMINISTRADOR',
  ACUERDO_AUTOAPROBACION: 'ACUERDO_AUTOAPROBACION',
  CUOTA_ACUERDO_TRANSICION_INVALIDA: 'CUOTA_ACUERDO_TRANSICION_INVALIDA',

  // ── Escalamiento (F6) ────────────────────────────────────────────────
  CARTERA_ETAPA_INICIAL_INVALIDA: 'CARTERA_ETAPA_INICIAL_INVALIDA',
  CARTERA_ETAPA_CONTEXTO_INMUTABLE: 'CARTERA_ETAPA_CONTEXTO_INMUTABLE',
  CARTERA_ETAPA_CONGELADA: 'CARTERA_ETAPA_CONGELADA',
  CARTERA_ETAPA_TRANSICION_INVALIDA: 'CARTERA_ETAPA_TRANSICION_INVALIDA',
  CARTERA_ETAPA_SIN_PROPUESTA: 'CARTERA_ETAPA_SIN_PROPUESTA',
  CARTERA_ETAPA_REQUIERE_ADMINISTRADOR: 'CARTERA_ETAPA_REQUIERE_ADMINISTRADOR',
  CARTERA_ETAPA_AUTOAPROBACION: 'CARTERA_ETAPA_AUTOAPROBACION',

  // ── Jurídico (F7) ────────────────────────────────────────────────────
  CERTIFICACION_REQUIERE_ADMINISTRADOR: 'CERTIFICACION_REQUIERE_ADMINISTRADOR',
  CERTIFICACION_INMUTABLE: 'CERTIFICACION_INMUTABLE',
  CERTIFICACION_TRANSICION_INVALIDA: 'CERTIFICACION_TRANSICION_INVALIDA',
  CERTIFICACION_ANULACION_SIN_MOTIVO: 'CERTIFICACION_ANULACION_SIN_MOTIVO',
  CASO_JURIDICO_REQUIERE_ADMINISTRADOR: 'CASO_JURIDICO_REQUIERE_ADMINISTRADOR',
  CASO_JURIDICO_CERTIFICACION_INVALIDA: 'CASO_JURIDICO_CERTIFICACION_INVALIDA',
  CASO_JURIDICO_ABOGADO_INVALIDO: 'CASO_JURIDICO_ABOGADO_INVALIDO',
  CASO_JURIDICO_CONTEXTO_INMUTABLE: 'CASO_JURIDICO_CONTEXTO_INMUTABLE',
  CASO_JURIDICO_CIERRE_REQUIERE_ADMINISTRADOR: 'CASO_JURIDICO_CIERRE_REQUIERE_ADMINISTRADOR',
  CASO_JURIDICO_INVALIDO: 'CASO_JURIDICO_INVALIDO',
  COSTA_JUDICIAL_INMUTABLE: 'COSTA_JUDICIAL_INMUTABLE',

  // ── Plantillas SMS ────────────────────────────────────────────────────
  SMS_UNKNOWN_EVENT: 'SMS_UNKNOWN_EVENT',
  SMS_BODY_TOO_LONG: 'SMS_BODY_TOO_LONG',
  SMS_UNKNOWN_FIELDS: 'SMS_UNKNOWN_FIELDS',
  SMS_INVALID_PHONE: 'SMS_INVALID_PHONE',
  SMS_TEMPLATE_NOT_FOUND: 'SMS_TEMPLATE_NOT_FOUND',
  SMS_EVENT_NOT_ACTIVE: 'SMS_EVENT_NOT_ACTIVE',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',

  // ── Plantillas de correo (Brevo templates) ─────────────────────────────
  EMAIL_UNKNOWN_EVENT: 'EMAIL_UNKNOWN_EVENT',
  EMAIL_BODY_TOO_SHORT: 'EMAIL_BODY_TOO_SHORT',
  EMAIL_UNKNOWN_FIELDS: 'EMAIL_UNKNOWN_FIELDS',
  EMAIL_MISSING_PARAMS_PREFIX: 'EMAIL_MISSING_PARAMS_PREFIX',
  EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',

  // ── Fuente de financiación (20260830210000, lista_tipos) ────────────────
  FUENTE_FINANCIACION_TIPO_SIN_MAPEO: 'FUENTE_FINANCIACION_TIPO_SIN_MAPEO',
  TIPO_FUENTE_INEXISTENTE: 'TIPO_FUENTE_INEXISTENTE',
  TIPO_FUENTE_INVALIDO: 'TIPO_FUENTE_INVALIDO',
  TIPO_FUENTE_TENANT_INCONSISTENTE: 'TIPO_FUENTE_TENANT_INCONSISTENTE',

  // ── Agrupaciones de predios (20260830250000) ─────────────────────────────
  AGRUPACION_INEXISTENTE: 'AGRUPACION_INEXISTENTE',
  AGRUPACION_TIPO_INVALIDO: 'AGRUPACION_TIPO_INVALIDO',
  AGRUPACION_TIPO_TENANT_INCONSISTENTE: 'AGRUPACION_TIPO_TENANT_INCONSISTENTE',
  AGRUPACION_TIPO_INACTIVO: 'AGRUPACION_TIPO_INACTIVO',
  AGRUPACION_CICLO: 'AGRUPACION_CICLO',
  AGRUPACION_PADRE_INEXISTENTE: 'AGRUPACION_PADRE_INEXISTENTE',
  AGRUPACION_TENANT_INCONSISTENTE: 'AGRUPACION_TENANT_INCONSISTENTE',
  AGRUPACION_PROFUNDIDAD_MAXIMA: 'AGRUPACION_PROFUNDIDAD_MAXIMA',

  // ── Centro de costo en presupuesto (20260830420000) ──────────────────────
  CENTRO_COSTO_INEXISTENTE: 'CENTRO_COSTO_INEXISTENTE',
  CENTRO_COSTO_INVALIDO: 'CENTRO_COSTO_INVALIDO',
  CENTRO_COSTO_TENANT_INCONSISTENTE: 'CENTRO_COSTO_TENANT_INCONSISTENTE',
  CENTRO_COSTO_INACTIVO: 'CENTRO_COSTO_INACTIVO',
} as const satisfies Record<string, string>

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
